### ISSUE TITLE
请问如何集成到项目中？不可以通过gradle集成吗？谢谢

### ISSUE THREAD

**Issue by xiaominglee4github** [LambdaXiao/StockChart-MPAndroidChart#6]

**Comment by LambdaXiao** [comment]
暂时没上传到maven，最好是直接添加为module，考虑到每个人用来画图表的数据是不一样的，需要稍微配置下代码，后期会通过gradle集成

xiaominglee4github <notifications@github.com> 于 2019年10月10日周四 17:28写道：
